services:
    caddy:
        container_name: caddy
        build:
          dockerfile: Dockerfile
        image: ghcr.io/irrisdev/caddy:latest
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
        networks:
            - caddy
        restart: unless-stopped
        volumes:
            - '$PWD/conf:/etc/caddy'
            - config:/config
            - data:/data

networks:
    caddy:
        name: caddy

volumes:
    config:
    data: